"""Wrap LLM-generated resume body HTML with the template's CSS."""

from __future__ import annotations

import re
from pathlib import Path

import importlib.resources

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

# Cache the style block extracted from template.html on first call.
_STYLE_CACHE: str | None = None


def _get_template_text(template_path: Path | None = None) -> str:
    if template_path is not None:
        return template_path.read_text(encoding="utf-8")

    try:
        ref = importlib.resources.files("ats_mcp") / "template.html"
        if ref.is_file():
            return ref.read_text(encoding="utf-8")
    except Exception:
        pass

    fallback_path = _PROJECT_ROOT / "template.html"
    return fallback_path.read_text(encoding="utf-8")


def _extract_style(template_path: Path | None = None) -> str:
    """Return the full ``<style>…</style>`` block from template.html."""
    global _STYLE_CACHE
    if _STYLE_CACHE is not None:
        return _STYLE_CACHE

    text = _get_template_text(template_path)
    match = re.search(r"(<style[\s\S]*?</style>)", text, re.IGNORECASE)
    if not match:
        raise ValueError("No <style> block found in template.html")
    _STYLE_CACHE = match.group(1)
    return _STYLE_CACHE


def get_template(template_path: Path | None = None) -> str:
    """Return the raw contents of template.html."""
    return _get_template_text(template_path)



def render_resume(body_html: str, template_path: Path | None = None) -> str:
    """Produce a full HTML document by combining the template CSS with *body_html*.

    The *body_html* is the complete ``<body>`` inner content generated by the
    IDE LLM.  This function wraps it in a proper ``<!DOCTYPE html>`` shell
    that carries the exact same ``<style>`` rules from ``template.html``.
    """
    style = _extract_style(template_path)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Resume</title>
    {style}
</head>
<body>
{body_html}
</body>
</html>"""
